-- BrewBuddy MVP prototype schema

create table if not exists public.beers (
  id bigint generated by default as identity primary key,
  name text not null,
  style text not null,
  abv numeric(4,2) not null
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  user_id text not null,
  beer_id bigint not null references public.beers(id) on delete cascade,
  rating int not null check (rating between 1 and 5)
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id text not null,
  beer_id bigint not null references public.beers(id) on delete cascade,
  unique (user_id, beer_id)
);

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null
);

create table if not exists public.availability (
  beer_id bigint not null references public.beers(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  in_stock boolean not null default false,
  primary key (beer_id, store_id)
);
